# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f5d840c5c10714d8b80b9041093449a34711d33c8553c5ea0fd3037bdf58fbfbfd0aeb3b14b377649a9ffa6ff832fdc34da82fc4b78a6c84a91fe65b35828a7

test:
  secret_key_base: 8bda2ca67db4a8546085130a3135fe2a6737fd59922e6c97a9e7bf28f1558769af3dad564a182eff094d0d89dc0c66380e597f96c85c91f8a0484d32776ed7cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
